///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MakeMyTrip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MakeMyTripRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("7cf8b46d-c687-4f16-bfce-cf02b6431f7c")]
    public partial class MakeMyTripRepository : RepoGenBaseFolder
    {
        static MakeMyTripRepository instance = new MakeMyTripRepository();
        MakeMyTripRepositoryFolders.MMTAppFolder _mmt;

        /// <summary>
        /// Gets the singleton class instance representing the MakeMyTripRepository element repository.
        /// </summary>
        [RepositoryFolder("7cf8b46d-c687-4f16-bfce-cf02b6431f7c")]
        public static MakeMyTripRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MakeMyTripRepository() 
            : base("MakeMyTripRepository", "/", null, 0, false, "7cf8b46d-c687-4f16-bfce-cf02b6431f7c", ".\\RepositoryImages\\MakeMyTripRepository7cf8b46d.rximgres")
        {
            _mmt = new MakeMyTripRepositoryFolders.MMTAppFolder(this);
        }

#region Variables

        string _R_Login = "Log In";

        /// <summary>
        /// Gets or sets the value of variable R_Login.
        /// </summary>
        [TestVariable("b91f8b84-ebdc-4c9d-8b84-12ccf082a4a7")]
        public string R_Login
        {
            get { return _R_Login; }
            set { _R_Login = value; }
        }

        string _R_Index = "1";

        /// <summary>
        /// Gets or sets the value of variable R_Index.
        /// </summary>
        [TestVariable("ff3dec9f-f7f8-4c8e-83fc-f27a549036ca")]
        public string R_Index
        {
            get { return _R_Index; }
            set { _R_Index = value; }
        }

        string _R_DropDownOption = "";

        /// <summary>
        /// Gets or sets the value of variable R_DropDownOption.
        /// </summary>
        [TestVariable("1260d464-40ff-4834-82f3-92f851aeb304")]
        public string R_DropDownOption
        {
            get { return _R_DropDownOption; }
            set { _R_DropDownOption = value; }
        }

        string _R_Day = "12";

        /// <summary>
        /// Gets or sets the value of variable R_Day.
        /// </summary>
        [TestVariable("e4e606b0-0ea8-42d8-889c-6957441a47ee")]
        public string R_Day
        {
            get { return _R_Day; }
            set { _R_Day = value; }
        }

        string _RL_Search = "";

        /// <summary>
        /// Gets or sets the value of variable RL_Search.
        /// </summary>
        [TestVariable("f30cf43b-6ed0-42ed-892c-489fcd3adb08")]
        public string RL_Search
        {
            get { return _RL_Search; }
            set { _RL_Search = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7cf8b46d-c687-4f16-bfce-cf02b6431f7c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MMT folder.
        /// </summary>
        [RepositoryFolder("ee98a101-93a4-4936-ae78-ad971e4db8ed")]
        public virtual MakeMyTripRepositoryFolders.MMTAppFolder MMT
        {
            get { return _mmt; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MakeMyTripRepositoryFolders
    {
        /// <summary>
        /// The MMTAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee98a101-93a4-4936-ae78-ad971e4db8ed")]
        public partial class MMTAppFolder : RepoGenBaseFolder
        {
            MakeMyTripRepositoryFolders.DateFolder _date;
            MakeMyTripRepositoryFolders.SearchResultFolder _searchresult;
            MakeMyTripRepositoryFolders.ReviewFolder _review;
            MakeMyTripRepositoryFolders.TabFolder _tab;
            MakeMyTripRepositoryFolders.FswInputBoxDatesInactiveWidgetFolder _fswinputboxdatesinactivewidget;
            RepoItemInfo _homebuttonInfo;
            RepoItemInfo _flightInfo;
            RepoItemInfo _roundtripInfo;
            RepoItemInfo _fromInfo;
            RepoItemInfo _fromsuggestionoptionInfo;
            RepoItemInfo _fromoptionlistInfo;
            RepoItemInfo _toInfo;
            RepoItemInfo _tosuggestionoptionInfo;
            RepoItemInfo _recentsearchlistInfo;
            RepoItemInfo _popularcitieslistInfo;
            RepoItemInfo _searchInfo;

            /// <summary>
            /// Creates a new MMT  folder.
            /// </summary>
            public MMTAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MMT", "/dom[@domain='www.makemytrip.com' and @visible='true']", parentFolder, 30000, null, true, "ee98a101-93a4-4936-ae78-ad971e4db8ed", "")
            {
                _date = new MakeMyTripRepositoryFolders.DateFolder(this);
                _searchresult = new MakeMyTripRepositoryFolders.SearchResultFolder(this);
                _review = new MakeMyTripRepositoryFolders.ReviewFolder(this);
                _tab = new MakeMyTripRepositoryFolders.TabFolder(this);
                _fswinputboxdatesinactivewidget = new MakeMyTripRepositoryFolders.FswInputBoxDatesInactiveWidgetFolder(this);
                _homebuttonInfo = new RepoItemInfo(this, "HomeButton", ".//div[#'SW']//a", 30000, null, "02b37266-4019-4381-8c53-989dbd616f95");
                _flightInfo = new RepoItemInfo(this, "Flight", ".//div[#'SW']//div[@class='headerOuter']//li[@class='menu_Flights']//span[@innertext='Flights']", 30000, null, "0b4b86c4-16b1-45e2-b9db-dabbf6e78137");
                _roundtripInfo = new RepoItemInfo(this, "RoundTrip", ".//div[#'root']//div[@class='makeFlex']/ul/li[@innertext='Round Trip']", 30000, null, "4a6bc851-0156-4ade-b0a8-424cca5bb687");
                _fromInfo = new RepoItemInfo(this, "From", ".//input[#'fromCity']", 30000, null, "489478f8-1dc4-48b6-9adc-7a7d1894dc6f");
                _fromsuggestionoptionInfo = new RepoItemInfo(this, "FromSuggestionOption", ".//div[#'react-autowhatever-1']//p[@innertext='SUGGESTIONS ']/../../ul/li//p[@innertext~$R_DropDownOption]", 30000, null, "43d93920-edee-479e-8144-ed470330def8");
                _fromoptionlistInfo = new RepoItemInfo(this, "FromOptionList", ".//div[#'react-autowhatever-1']", 30000, null, "32dd1723-04f5-49f8-b027-93daafe8d8cc");
                _toInfo = new RepoItemInfo(this, "To", ".//input[#'toCity']", 30000, null, "3c1e2843-0c40-4c6d-aed2-05ca9e82fd16");
                _tosuggestionoptionInfo = new RepoItemInfo(this, "ToSuggestionOption", ".//div[#'react-autowhatever-1']//p[@innertext='SUGGESTIONS ']/../../ul/li//p[@innertext~$R_DropDownOption]", 30000, null, "19dddf5d-5545-47b8-a860-9f4b98fa1877");
                _recentsearchlistInfo = new RepoItemInfo(this, "RecentSearchList", ".//div[#'react-autowhatever-1']//p[@innertext='RECENT SEARCHES']/../../ul", 30000, null, "4391044f-43ef-43a5-9266-c14041fd7477");
                _popularcitieslistInfo = new RepoItemInfo(this, "PopularCitiesList", ".//div[#'react-autowhatever-1']//p[@innertext='POPULAR CITIES']/../../ul", 30000, null, "f6ff3e12-9d72-48cc-9743-c3f18d510f55");
                _searchInfo = new RepoItemInfo(this, "Search", ".//div[#'root']/div/div[2]/div//a[@innertext=$RL_Search]", 30000, null, "b83aa44b-1f38-4818-9b0f-27a7012e2ac5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee98a101-93a4-4936-ae78-ad971e4db8ed")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee98a101-93a4-4936-ae78-ad971e4db8ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomeButton item.
            /// </summary>
            [RepositoryItem("02b37266-4019-4381-8c53-989dbd616f95")]
            public virtual Ranorex.ATag HomeButton
            {
                get
                {
                    return _homebuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HomeButton item info.
            /// </summary>
            [RepositoryItemInfo("02b37266-4019-4381-8c53-989dbd616f95")]
            public virtual RepoItemInfo HomeButtonInfo
            {
                get
                {
                    return _homebuttonInfo;
                }
            }

            /// <summary>
            /// The Flight item.
            /// </summary>
            [RepositoryItem("0b4b86c4-16b1-45e2-b9db-dabbf6e78137")]
            public virtual Ranorex.SpanTag Flight
            {
                get
                {
                    return _flightInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Flight item info.
            /// </summary>
            [RepositoryItemInfo("0b4b86c4-16b1-45e2-b9db-dabbf6e78137")]
            public virtual RepoItemInfo FlightInfo
            {
                get
                {
                    return _flightInfo;
                }
            }

            /// <summary>
            /// The RoundTrip item.
            /// </summary>
            [RepositoryItem("4a6bc851-0156-4ade-b0a8-424cca5bb687")]
            public virtual Ranorex.LiTag RoundTrip
            {
                get
                {
                    return _roundtripInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The RoundTrip item info.
            /// </summary>
            [RepositoryItemInfo("4a6bc851-0156-4ade-b0a8-424cca5bb687")]
            public virtual RepoItemInfo RoundTripInfo
            {
                get
                {
                    return _roundtripInfo;
                }
            }

            /// <summary>
            /// The From item.
            /// </summary>
            [RepositoryItem("489478f8-1dc4-48b6-9adc-7a7d1894dc6f")]
            public virtual Ranorex.InputTag From
            {
                get
                {
                    return _fromInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The From item info.
            /// </summary>
            [RepositoryItemInfo("489478f8-1dc4-48b6-9adc-7a7d1894dc6f")]
            public virtual RepoItemInfo FromInfo
            {
                get
                {
                    return _fromInfo;
                }
            }

            /// <summary>
            /// The FromSuggestionOption item.
            /// </summary>
            [RepositoryItem("43d93920-edee-479e-8144-ed470330def8")]
            public virtual Ranorex.PTag FromSuggestionOption
            {
                get
                {
                    return _fromsuggestionoptionInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The FromSuggestionOption item info.
            /// </summary>
            [RepositoryItemInfo("43d93920-edee-479e-8144-ed470330def8")]
            public virtual RepoItemInfo FromSuggestionOptionInfo
            {
                get
                {
                    return _fromsuggestionoptionInfo;
                }
            }

            /// <summary>
            /// The FromOptionList item.
            /// </summary>
            [RepositoryItem("32dd1723-04f5-49f8-b027-93daafe8d8cc")]
            public virtual Ranorex.DivTag FromOptionList
            {
                get
                {
                    return _fromoptionlistInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FromOptionList item info.
            /// </summary>
            [RepositoryItemInfo("32dd1723-04f5-49f8-b027-93daafe8d8cc")]
            public virtual RepoItemInfo FromOptionListInfo
            {
                get
                {
                    return _fromoptionlistInfo;
                }
            }

            /// <summary>
            /// The To item.
            /// </summary>
            [RepositoryItem("3c1e2843-0c40-4c6d-aed2-05ca9e82fd16")]
            public virtual Ranorex.InputTag To
            {
                get
                {
                    return _toInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The To item info.
            /// </summary>
            [RepositoryItemInfo("3c1e2843-0c40-4c6d-aed2-05ca9e82fd16")]
            public virtual RepoItemInfo ToInfo
            {
                get
                {
                    return _toInfo;
                }
            }

            /// <summary>
            /// The ToSuggestionOption item.
            /// </summary>
            [RepositoryItem("19dddf5d-5545-47b8-a860-9f4b98fa1877")]
            public virtual Ranorex.PTag ToSuggestionOption
            {
                get
                {
                    return _tosuggestionoptionInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ToSuggestionOption item info.
            /// </summary>
            [RepositoryItemInfo("19dddf5d-5545-47b8-a860-9f4b98fa1877")]
            public virtual RepoItemInfo ToSuggestionOptionInfo
            {
                get
                {
                    return _tosuggestionoptionInfo;
                }
            }

            /// <summary>
            /// The RecentSearchList item.
            /// </summary>
            [RepositoryItem("4391044f-43ef-43a5-9266-c14041fd7477")]
            public virtual Ranorex.UlTag RecentSearchList
            {
                get
                {
                    return _recentsearchlistInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The RecentSearchList item info.
            /// </summary>
            [RepositoryItemInfo("4391044f-43ef-43a5-9266-c14041fd7477")]
            public virtual RepoItemInfo RecentSearchListInfo
            {
                get
                {
                    return _recentsearchlistInfo;
                }
            }

            /// <summary>
            /// The PopularCitiesList item.
            /// </summary>
            [RepositoryItem("f6ff3e12-9d72-48cc-9743-c3f18d510f55")]
            public virtual Ranorex.UlTag PopularCitiesList
            {
                get
                {
                    return _popularcitieslistInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The PopularCitiesList item info.
            /// </summary>
            [RepositoryItemInfo("f6ff3e12-9d72-48cc-9743-c3f18d510f55")]
            public virtual RepoItemInfo PopularCitiesListInfo
            {
                get
                {
                    return _popularcitieslistInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("b83aa44b-1f38-4818-9b0f-27a7012e2ac5")]
            public virtual Ranorex.ATag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("b83aa44b-1f38-4818-9b0f-27a7012e2ac5")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Date folder.
            /// </summary>
            [RepositoryFolder("96fc6a85-25d2-46c0-9815-14424a864569")]
            public virtual MakeMyTripRepositoryFolders.DateFolder Date
            {
                get { return _date; }
            }

            /// <summary>
            /// The SearchResult folder.
            /// </summary>
            [RepositoryFolder("8b89dd75-9a67-476b-978c-38731d41ce85")]
            public virtual MakeMyTripRepositoryFolders.SearchResultFolder SearchResult
            {
                get { return _searchresult; }
            }

            /// <summary>
            /// The Review folder.
            /// </summary>
            [RepositoryFolder("1b97dfe1-bd10-4ba3-91e4-c60aff14d74f")]
            public virtual MakeMyTripRepositoryFolders.ReviewFolder Review
            {
                get { return _review; }
            }

            /// <summary>
            /// The Tab folder.
            /// </summary>
            [RepositoryFolder("74977c83-75d5-4e0e-ab1e-ccb90f586dbb")]
            public virtual MakeMyTripRepositoryFolders.TabFolder Tab
            {
                get { return _tab; }
            }

            /// <summary>
            /// The FswInputBoxDatesInactiveWidget folder.
            /// </summary>
            [RepositoryFolder("b0acfd19-095f-4ae8-89ca-fbe029e024c2")]
            public virtual MakeMyTripRepositoryFolders.FswInputBoxDatesInactiveWidgetFolder FswInputBoxDatesInactiveWidget
            {
                get { return _fswinputboxdatesinactivewidget; }
            }
        }

        /// <summary>
        /// The DateFolder folder.
        /// </summary>
        [RepositoryFolder("96fc6a85-25d2-46c0-9815-14424a864569")]
        public partial class DateFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departdateInfo;
            RepoItemInfo _departreturndateInfo;

            /// <summary>
            /// Creates a new Date  folder.
            /// </summary>
            public DateFolder(RepoGenBaseFolder parentFolder) :
                    base("Date", "", parentFolder, 0, null, false, "96fc6a85-25d2-46c0-9815-14424a864569", "")
            {
                _departdateInfo = new RepoItemInfo(this, "DepartDate", ".//input[#'departure']", 30000, null, "06705a54-e14f-4201-8858-908cdbfa7392");
                _departreturndateInfo = new RepoItemInfo(this, "DepartReturnDate", ".//div[#'root']//div[@class='datePickerContainer']//div[@class='DayPicker-Months']/div[@childindex=$R_Index]/div/..//div[@class~'DayPicker-Day' and @aria-disabled='false']/div/p[@innertext=$R_Day and @visible='true']", 30000, null, "df15b8df-12cb-493a-abab-5835f23f156e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96fc6a85-25d2-46c0-9815-14424a864569")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DepartDate item.
            /// </summary>
            [RepositoryItem("06705a54-e14f-4201-8858-908cdbfa7392")]
            public virtual Ranorex.InputTag DepartDate
            {
                get
                {
                    return _departdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DepartDate item info.
            /// </summary>
            [RepositoryItemInfo("06705a54-e14f-4201-8858-908cdbfa7392")]
            public virtual RepoItemInfo DepartDateInfo
            {
                get
                {
                    return _departdateInfo;
                }
            }

            /// <summary>
            /// The DepartReturnDate item.
            /// </summary>
            [RepositoryItem("df15b8df-12cb-493a-abab-5835f23f156e")]
            public virtual Ranorex.PTag DepartReturnDate
            {
                get
                {
                    return _departreturndateInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The DepartReturnDate item info.
            /// </summary>
            [RepositoryItemInfo("df15b8df-12cb-493a-abab-5835f23f156e")]
            public virtual RepoItemInfo DepartReturnDateInfo
            {
                get
                {
                    return _departreturndateInfo;
                }
            }
        }

        /// <summary>
        /// The SearchResultFolder folder.
        /// </summary>
        [RepositoryFolder("8b89dd75-9a67-476b-978c-38731d41ce85")]
        public partial class SearchResultFolder : RepoGenBaseFolder
        {
            MakeMyTripRepositoryFolders.DepartFolder _depart;
            MakeMyTripRepositoryFolders.ReturnFolder _return;
            RepoItemInfo _booknowInfo;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new SearchResult  folder.
            /// </summary>
            public SearchResultFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchResult", "", parentFolder, 0, null, false, "8b89dd75-9a67-476b-978c-38731d41ce85", "")
            {
                _depart = new MakeMyTripRepositoryFolders.DepartFolder(this);
                _return = new MakeMyTripRepositoryFolders.ReturnFolder(this);
                _booknowInfo = new RepoItemInfo(this, "BookNow", ".//div[#'listing-id']//button[@innertext='Book Now']", 30000, null, "efba82bd-ee3c-4ec9-9fe0-9363a7b84cd4");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//div[#'listing-id']//button[@innertext='Continue']", 30000, null, "0aaa2f2f-8ece-42a4-a7db-5494d3aa0ed2");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b89dd75-9a67-476b-978c-38731d41ce85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BookNow item.
            /// </summary>
            [RepositoryItem("efba82bd-ee3c-4ec9-9fe0-9363a7b84cd4")]
            public virtual Ranorex.ButtonTag BookNow
            {
                get
                {
                    return _booknowInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BookNow item info.
            /// </summary>
            [RepositoryItemInfo("efba82bd-ee3c-4ec9-9fe0-9363a7b84cd4")]
            public virtual RepoItemInfo BookNowInfo
            {
                get
                {
                    return _booknowInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("0aaa2f2f-8ece-42a4-a7db-5494d3aa0ed2")]
            public virtual Ranorex.ButtonTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("0aaa2f2f-8ece-42a4-a7db-5494d3aa0ed2")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The Depart folder.
            /// </summary>
            [RepositoryFolder("c6b2dca0-f300-46e6-b2fc-3f7005213bc2")]
            public virtual MakeMyTripRepositoryFolders.DepartFolder Depart
            {
                get { return _depart; }
            }

            /// <summary>
            /// The Return folder.
            /// </summary>
            [RepositoryFolder("2bcc9de4-4262-46c9-a69b-f79ab36a7b83")]
            public virtual MakeMyTripRepositoryFolders.ReturnFolder Return
            {
                get { return _return; }
            }
        }

        /// <summary>
        /// The DepartFolder folder.
        /// </summary>
        [RepositoryFolder("c6b2dca0-f300-46e6-b2fc-3f7005213bc2")]
        public partial class DepartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departuresortInfo;
            RepoItemInfo _firstflightInfo;

            /// <summary>
            /// Creates a new Depart  folder.
            /// </summary>
            public DepartFolder(RepoGenBaseFolder parentFolder) :
                    base("Depart", "", parentFolder, 0, null, false, "c6b2dca0-f300-46e6-b2fc-3f7005213bc2", "")
            {
                _departuresortInfo = new RepoItemInfo(this, "DepartureSort", ".//div[#'sorting-togglers']//span[@innertext='Departure']", 30000, null, "aab1b41e-3fe6-4346-83ca-2b1b0945295a");
                _firstflightInfo = new RepoItemInfo(this, "FirstFlight", ".//div[#'listing-id']//div[@childindex='0' and @class='paneView']/div[@class='listingCardWrap']/div/label[1]", 30000, null, "26101ef5-6cea-4dd9-9750-8d63d1a1835f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c6b2dca0-f300-46e6-b2fc-3f7005213bc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DepartureSort item.
            /// </summary>
            [RepositoryItem("aab1b41e-3fe6-4346-83ca-2b1b0945295a")]
            public virtual Ranorex.SpanTag DepartureSort
            {
                get
                {
                    return _departuresortInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DepartureSort item info.
            /// </summary>
            [RepositoryItemInfo("aab1b41e-3fe6-4346-83ca-2b1b0945295a")]
            public virtual RepoItemInfo DepartureSortInfo
            {
                get
                {
                    return _departuresortInfo;
                }
            }

            /// <summary>
            /// The FirstFlight item.
            /// </summary>
            [RepositoryItem("26101ef5-6cea-4dd9-9750-8d63d1a1835f")]
            public virtual Ranorex.LabelTag FirstFlight
            {
                get
                {
                    return _firstflightInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The FirstFlight item info.
            /// </summary>
            [RepositoryItemInfo("26101ef5-6cea-4dd9-9750-8d63d1a1835f")]
            public virtual RepoItemInfo FirstFlightInfo
            {
                get
                {
                    return _firstflightInfo;
                }
            }
        }

        /// <summary>
        /// The ReturnFolder folder.
        /// </summary>
        [RepositoryFolder("2bcc9de4-4262-46c9-a69b-f79ab36a7b83")]
        public partial class ReturnFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departuresortInfo;
            RepoItemInfo _firstflightInfo;

            /// <summary>
            /// Creates a new Return  folder.
            /// </summary>
            public ReturnFolder(RepoGenBaseFolder parentFolder) :
                    base("Return", "", parentFolder, 0, null, false, "2bcc9de4-4262-46c9-a69b-f79ab36a7b83", "")
            {
                _departuresortInfo = new RepoItemInfo(this, "DepartureSort", ".//div[#'listing-id']/div/div[2]/?/?/div[@id='sorting-togglers']/div[1]//span[@innertext='Departure']", 30000, null, "0ceae54e-60c8-47f4-93c7-291d2b13d64a");
                _firstflightInfo = new RepoItemInfo(this, "FirstFlight", ".//div[#'listing-id']//div[@childindex='1' and @class='paneView']/div[@class='listingCardWrap']/div/label[1]", 30000, null, "0a66157e-275e-4cc6-ab03-6a9e60efb8e8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2bcc9de4-4262-46c9-a69b-f79ab36a7b83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DepartureSort item.
            /// </summary>
            [RepositoryItem("0ceae54e-60c8-47f4-93c7-291d2b13d64a")]
            public virtual Ranorex.SpanTag DepartureSort
            {
                get
                {
                    return _departuresortInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DepartureSort item info.
            /// </summary>
            [RepositoryItemInfo("0ceae54e-60c8-47f4-93c7-291d2b13d64a")]
            public virtual RepoItemInfo DepartureSortInfo
            {
                get
                {
                    return _departuresortInfo;
                }
            }

            /// <summary>
            /// The FirstFlight item.
            /// </summary>
            [RepositoryItem("0a66157e-275e-4cc6-ab03-6a9e60efb8e8")]
            public virtual Ranorex.LabelTag FirstFlight
            {
                get
                {
                    return _firstflightInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The FirstFlight item info.
            /// </summary>
            [RepositoryItemInfo("0a66157e-275e-4cc6-ab03-6a9e60efb8e8")]
            public virtual RepoItemInfo FirstFlightInfo
            {
                get
                {
                    return _firstflightInfo;
                }
            }
        }

        /// <summary>
        /// The ReviewFolder folder.
        /// </summary>
        [RepositoryFolder("1b97dfe1-bd10-4ba3-91e4-c60aff14d74f")]
        public partial class ReviewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _basefareInfo;
            RepoItemInfo _feesurchargesInfo;
            RepoItemInfo _otherservicesInfo;
            RepoItemInfo _totalamountInfo;

            /// <summary>
            /// Creates a new Review  folder.
            /// </summary>
            public ReviewFolder(RepoGenBaseFolder parentFolder) :
                    base("Review", "", parentFolder, 0, null, false, "1b97dfe1-bd10-4ba3-91e4-c60aff14d74f", "")
            {
                _basefareInfo = new RepoItemInfo(this, "BaseFare", ".//div[@class='review-page']//div[@class='fareSmry-sctn']//span[@innertext='Base Fare']/../../../div[2]/p/span[2]/span", 45000, null, "3218111c-c5db-4ede-9401-ed6f0e71021a");
                _feesurchargesInfo = new RepoItemInfo(this, "FeeSurcharges", ".//div[#'root']/div/div[2]/div[2]/div[1]/div[2]/div[1]/div/div[2]//span[@innertext='Fee & Surcharges']/../../span", 45000, null, "1a6c72ef-08d0-44d4-bac2-bfd0ffdf144b");
                _otherservicesInfo = new RepoItemInfo(this, "OtherServices", ".//div[#'root']/div/div[2]/div[2]/div[1]/div[2]/div[1]/div/div[3]//span[@innertext='Other Services']/../../span", 45000, null, "d06cf2c2-5b6a-48af-8da5-d09694bb5c63");
                _totalamountInfo = new RepoItemInfo(this, "TotalAmount", ".//div[#'root']//div[@class='review-page']//div[@class='fareSmry-sctn reqPad-fareSmry-sctn']//span[@innertext~'Total Amount']/../../../span[2]/span/span", 45000, null, "563bc7f2-16d9-4900-9424-0dcccc45f332");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b97dfe1-bd10-4ba3-91e4-c60aff14d74f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BaseFare item.
            /// </summary>
            [RepositoryItem("3218111c-c5db-4ede-9401-ed6f0e71021a")]
            public virtual Ranorex.SpanTag BaseFare
            {
                get
                {
                    return _basefareInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BaseFare item info.
            /// </summary>
            [RepositoryItemInfo("3218111c-c5db-4ede-9401-ed6f0e71021a")]
            public virtual RepoItemInfo BaseFareInfo
            {
                get
                {
                    return _basefareInfo;
                }
            }

            /// <summary>
            /// The FeeSurcharges item.
            /// </summary>
            [RepositoryItem("1a6c72ef-08d0-44d4-bac2-bfd0ffdf144b")]
            public virtual Ranorex.SpanTag FeeSurcharges
            {
                get
                {
                    return _feesurchargesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The FeeSurcharges item info.
            /// </summary>
            [RepositoryItemInfo("1a6c72ef-08d0-44d4-bac2-bfd0ffdf144b")]
            public virtual RepoItemInfo FeeSurchargesInfo
            {
                get
                {
                    return _feesurchargesInfo;
                }
            }

            /// <summary>
            /// The OtherServices item.
            /// </summary>
            [RepositoryItem("d06cf2c2-5b6a-48af-8da5-d09694bb5c63")]
            public virtual Ranorex.SpanTag OtherServices
            {
                get
                {
                    return _otherservicesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The OtherServices item info.
            /// </summary>
            [RepositoryItemInfo("d06cf2c2-5b6a-48af-8da5-d09694bb5c63")]
            public virtual RepoItemInfo OtherServicesInfo
            {
                get
                {
                    return _otherservicesInfo;
                }
            }

            /// <summary>
            /// The TotalAmount item.
            /// </summary>
            [RepositoryItem("563bc7f2-16d9-4900-9424-0dcccc45f332")]
            public virtual Ranorex.SpanTag TotalAmount
            {
                get
                {
                    return _totalamountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TotalAmount item info.
            /// </summary>
            [RepositoryItemInfo("563bc7f2-16d9-4900-9424-0dcccc45f332")]
            public virtual RepoItemInfo TotalAmountInfo
            {
                get
                {
                    return _totalamountInfo;
                }
            }
        }

        /// <summary>
        /// The TabFolder folder.
        /// </summary>
        [RepositoryFolder("74977c83-75d5-4e0e-ab1e-ccb90f586dbb")]
        public partial class TabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _currenttabcloseInfo;

            /// <summary>
            /// Creates a new Tab  folder.
            /// </summary>
            public TabFolder(RepoGenBaseFolder parentFolder) :
                    base("Tab", "", parentFolder, 0, null, false, "74977c83-75d5-4e0e-ab1e-ccb90f586dbb", "")
            {
                _currenttabcloseInfo = new RepoItemInfo(this, "CurrentTabClose", "../form[@title~'^MakeMyTrip']/container[@accessiblename~'^MakeMyTrip']//tabpagelist[@accessiblerole='PageTabList']//tabpage[@accessiblerole='PageTab' and @title='MakeMyTrip' and @visible='true' and @selected='true']//*[@text='Close' and @visible='true']", 30000, null, "85294718-db2d-4dea-876a-d9e69f7da39f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("74977c83-75d5-4e0e-ab1e-ccb90f586dbb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CurrentTabClose item.
            /// </summary>
            [RepositoryItem("85294718-db2d-4dea-876a-d9e69f7da39f")]
            public virtual Ranorex.Unknown CurrentTabClose
            {
                get
                {
                    return _currenttabcloseInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The CurrentTabClose item info.
            /// </summary>
            [RepositoryItemInfo("85294718-db2d-4dea-876a-d9e69f7da39f")]
            public virtual RepoItemInfo CurrentTabCloseInfo
            {
                get
                {
                    return _currenttabcloseInfo;
                }
            }
        }

        /// <summary>
        /// The FswInputBoxDatesInactiveWidgetFolder folder.
        /// </summary>
        [RepositoryFolder("b0acfd19-095f-4ae8-89ca-fbe029e024c2")]
        public partial class FswInputBoxDatesInactiveWidgetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ptag30Info;
            RepoItemInfo _ptag8Info;
            RepoItemInfo _spantagjunInfo;

            /// <summary>
            /// Creates a new FswInputBoxDatesInactiveWidget  folder.
            /// </summary>
            public FswInputBoxDatesInactiveWidgetFolder(RepoGenBaseFolder parentFolder) :
                    base("FswInputBoxDatesInactiveWidget", ".//div[#'root']/div/div[2]/div/div[1]/div[2]/div[1]/div[3]", parentFolder, 30000, null, false, "b0acfd19-095f-4ae8-89ca-fbe029e024c2", "")
            {
                _ptag30Info = new RepoItemInfo(this, "PTag30", "div[1]/div/div/div/div[2]/div/div[2]/div[1]/div[3]/div[5]/div[4]/?/?/p[@innertext='30']", 30000, null, "56dca57f-42ff-4e55-a416-8c4b0b5311ab");
                _ptag8Info = new RepoItemInfo(this, "PTag8", "div[1]/div/div/div/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[5]/?/?/p[@innertext='8']", 30000, null, "0626d505-f5dc-4a90-a247-0df63dcfb51f");
                _spantagjunInfo = new RepoItemInfo(this, "SpanTagJun", "label/p[1]/span[@innertext='Jun']", 30000, null, "229ddb3a-d9ae-43ea-b3a9-819e3b5e9e5a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b0acfd19-095f-4ae8-89ca-fbe029e024c2")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b0acfd19-095f-4ae8-89ca-fbe029e024c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PTag30 item.
            /// </summary>
            [RepositoryItem("56dca57f-42ff-4e55-a416-8c4b0b5311ab")]
            public virtual Ranorex.PTag PTag30
            {
                get
                {
                    return _ptag30Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTag30 item info.
            /// </summary>
            [RepositoryItemInfo("56dca57f-42ff-4e55-a416-8c4b0b5311ab")]
            public virtual RepoItemInfo PTag30Info
            {
                get
                {
                    return _ptag30Info;
                }
            }

            /// <summary>
            /// The PTag8 item.
            /// </summary>
            [RepositoryItem("0626d505-f5dc-4a90-a247-0df63dcfb51f")]
            public virtual Ranorex.PTag PTag8
            {
                get
                {
                    return _ptag8Info.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTag8 item info.
            /// </summary>
            [RepositoryItemInfo("0626d505-f5dc-4a90-a247-0df63dcfb51f")]
            public virtual RepoItemInfo PTag8Info
            {
                get
                {
                    return _ptag8Info;
                }
            }

            /// <summary>
            /// The SpanTagJun item.
            /// </summary>
            [RepositoryItem("229ddb3a-d9ae-43ea-b3a9-819e3b5e9e5a")]
            public virtual Ranorex.SpanTag SpanTagJun
            {
                get
                {
                    return _spantagjunInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagJun item info.
            /// </summary>
            [RepositoryItemInfo("229ddb3a-d9ae-43ea-b3a9-819e3b5e9e5a")]
            public virtual RepoItemInfo SpanTagJunInfo
            {
                get
                {
                    return _spantagjunInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}